"""Added is_sold attribute to Product model

Revision ID: 88d5e83c7213
Revises: 
Create Date: 2024-02-27 16:41:43.301990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d5e83c7213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sold', sa.Boolean(), nullable=True))

    op.execute('UPDATE products SET is_sold = false WHERE is_sold IS NULL')

    # Alter column to be non-nullable
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_sold', existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_sold')

    # ### end Alembic commands ###
